#!/usr/bin/env bash
set -euo pipefail

step() { printf "\033[1;34m[STEP]\033[0m %s\n" "$*"; }
info() { printf "\033[1;32m[INFO]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[WARN]\033[0m %s\n" "$*"; }
fail() { printf "\033[1;31m[FAIL]\033[0m %s\n" "$*" >&2; exit 1; }

usage() {
  cat <<'USAGE'
JackPack Raspberry Pi 5 installer

Usage:
  sudo ./scripts/install_packjack_rpi5.sh [options]

Options:
  --non-interactive        Use env/defaults without prompts.
  --start-now              Start/restart JackPack services after install.
  --no-packages            Skip apt package installation.
  --install-dir PATH       Install/sync project to PATH. Default: /root/JackPack.
  --ssid NAME              Control AP SSID. Default: JackPack.
  --password PASS          Control AP WPA2 password, at least 8 chars.
  --ap-iface IFACE         Onboard/control AP interface. Default: wlan0.
  --attack-iface IFACE     External payload WiFi interface. Default: wlan1.
  --wired-iface IFACE      Built-in wired target interface. Default: eth0.
  --hostname NAME          Local mDNS hostname. Default: jackpack.
  --ap-address CIDR        AP IPv4/CIDR. Default: 10.66.0.1/24.
  --channel CHANNEL        AP channel. Default: 6.
  --web-port PORT          WebUI port. Default: 8080.
  --ws-port PORT           WebSocket port. Default: 8765.
  -h, --help               Show this help.

Environment variables with the same names are also honored:
  JACKPACK_AP_SSID, JACKPACK_AP_PASSWORD, JACKPACK_AP_IFACE,
  JACKPACK_ATTACK_IFACE, JACKPACK_WIRED_IFACE, JACKPACK_HOSTNAME,
  JACKPACK_AP_ADDRESS, JACKPACK_AP_CHANNEL, RJ_WEB_PORT, RJ_WS_PORT,
  JACKPACK_INSTALL_DIR.
USAGE
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    fail "Run as root: sudo -i && ./scripts/install_packjack_rpi5.sh"
  fi
}

prompt() {
  local var_name="$1"
  local label="$2"
  local default_value="$3"
  local secret="${4:-0}"
  local value=""
  if [ "$NON_INTERACTIVE" -eq 1 ]; then
    printf -v "$var_name" '%s' "$default_value"
    return
  fi
  if [ "$secret" -eq 1 ]; then
    read -r -s -p "$label [$default_value]: " value
    printf "\n"
  else
    read -r -p "$label [$default_value]: " value
  fi
  value="${value:-$default_value}"
  printf -v "$var_name" '%s' "$value"
}

is_valid_port() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
  esac
  [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

normalize_hostname() {
  local value="$1"
  value="${value%.local}"
  printf '%s' "$value" | tr '[:upper:]' '[:lower:]'
}

is_valid_hostname() {
  local value="$1"
  [ -n "$value" ] || return 1
  [ "${#value}" -le 63 ] || return 1
  case "$value" in
    -*|*-|*[^a-z0-9-]*) return 1 ;;
  esac
  return 0
}

detect_wifi_by_path() {
  local want="$1"
  local fallback="$2"
  local iface devpath
  for dev in /sys/class/net/wlan*; do
    [ -e "$dev" ] || continue
    iface="$(basename "$dev")"
    devpath="$(readlink -f "$dev/device" 2>/dev/null || true)"
    case "$want" in
      onboard)
        if printf '%s' "$devpath" | grep -q 'mmc'; then
          printf '%s' "$iface"
          return
        fi
        ;;
      usb)
        if printf '%s' "$devpath" | grep -q 'usb'; then
          printf '%s' "$iface"
          return
        fi
        ;;
    esac
  done
  printf '%s' "$fallback"
}

random_token() {
  od -An -N4 -tx1 /dev/urandom | tr -d ' \n'
}

write_env_file() {
  local path="$1"
  local tmp="${path}.tmp"
  mkdir -p "$(dirname "$path")"
  cat >"$tmp" <<EOF
# JackPack runtime configuration
# Generated by scripts/install_packjack_rpi5.sh

JACKPACK_AP_IFACE=$AP_IFACE
JACKPACK_AP_SSID=$AP_SSID
JACKPACK_AP_PASSWORD=$AP_PASSWORD
JACKPACK_AP_ADDRESS=$AP_ADDRESS
JACKPACK_AP_CHANNEL=$AP_CHANNEL
JACKPACK_AP_CONNECTION=jackpack-ap
JACKPACK_ATTACK_IFACE=$ATTACK_IFACE
JACKPACK_WIRED_IFACE=$WIRED_IFACE
JACKPACK_HOSTNAME=$LOCAL_HOSTNAME
JACKPACK_INSTALL_DIR=$INSTALL_DIR

RJ_HEADLESS=1
RJ_WEB_HOST=0.0.0.0
RJ_WEB_PORT=$WEB_PORT
RJ_WS_HOST=0.0.0.0
RJ_WS_PORT=$WS_PORT
RJ_WEBUI_INTERFACES=$WIRED_IFACE,$AP_IFACE,tailscale0
PYTHONPATH=$INSTALL_DIR:$INSTALL_DIR/packjack/compat
RJ_FRAME_MIRROR=1
RJ_SHELL_CWD=$INSTALL_DIR
RJ_WEB_AUTH_FILE=/etc/packjack/webui_auth.json
RJ_WEB_AUTH_SECRET_FILE=/etc/packjack/webui_session_secret
RJ_WS_TOKEN_FILE=/etc/packjack/ws_token
EOF
  install -m 600 "$tmp" "$path"
  rm -f "$tmp"
}

install_packages() {
  step "Installing OS packages"
  apt-get update
  apt-get install -y --no-install-recommends \
    network-manager avahi-daemon libnss-mdns rsync git procps iproute2 curl ca-certificates \
    python3 python3-pip python3-dev python3-pil python3-numpy \
    python3-scapy python3-netifaces python3-pyudev python3-serial python3-requests \
    python3-websockets python3-evdev python3-cryptography \
    nmap ncat tcpdump tshark arp-scan dsniff ettercap-text-only \
    aircrack-ng wireless-tools wpasupplicant iw hostapd dnsmasq-base \
    bridge-utils john sshpass autossh reaver ebtables fonts-dejavu-core \
    bluez python3-bluez gpsd gpsd-clients ffmpeg
}

setup_hostname() {
  step "Configuring friendly local URL"
  if command -v hostnamectl >/dev/null 2>&1; then
    hostnamectl set-hostname "$LOCAL_HOSTNAME" || warn "Could not set system hostname."
  else
    printf '%s\n' "$LOCAL_HOSTNAME" >/etc/hostname
    hostname "$LOCAL_HOSTNAME" >/dev/null 2>&1 || true
  fi

  if [ -f /etc/hosts ]; then
    if grep -q '^127\.0\.1\.1[[:space:]]' /etc/hosts; then
      sed -i "s/^127\\.0\\.1\\.1.*/127.0.1.1\t$LOCAL_HOSTNAME/" /etc/hosts
    else
      printf '127.0.1.1\t%s\n' "$LOCAL_HOSTNAME" >>/etc/hosts
    fi
  fi

  if command -v systemctl >/dev/null 2>&1; then
    systemctl enable avahi-daemon.service >/dev/null 2>&1 || warn "Could not enable avahi-daemon."
    systemctl restart avahi-daemon.service >/dev/null 2>&1 || true
  fi
  info "Friendly URL: http://$LOCAL_HOSTNAME.local:$WEB_PORT"
}

install_services() {
  step "Installing systemd services"
  cp "$INSTALL_DIR/deploy/systemd/packjack-"*.service /etc/systemd/system/
  if [ "$INSTALL_DIR" != "/root/JackPack" ]; then
    local escaped_dir
    escaped_dir="$(printf '%s' "$INSTALL_DIR" | sed 's/[\/&]/\\&/g')"
    sed -i "s/\/root\/JackPack/$escaped_dir/g" /etc/systemd/system/packjack-web.service /etc/systemd/system/packjack-ws.service
  fi
  cat >/etc/systemd/system/packjack-pin-wifi.service <<EOF
[Unit]
Description=JackPack stable WiFi interface names
DefaultDependencies=no
Before=network-pre.target NetworkManager.service
Wants=network-pre.target

[Service]
Type=oneshot
EnvironmentFile=-/etc/packjack/packjack.env
Environment=JACKPACK_INSTALL_DIR=$INSTALL_DIR
ExecStart=$INSTALL_DIR/scripts/pin_wifi_names.sh

[Install]
WantedBy=sysinit.target
EOF
  systemctl daemon-reload
  systemctl enable packjack-pin-wifi.service packjack-ap.service packjack-web.service packjack-ws.service
}

NON_INTERACTIVE=0
START_NOW=0
SKIP_PACKAGES=0
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${JACKPACK_INSTALL_DIR:-${PACKJACK_INSTALL_DIR:-/root/JackPack}}"
AP_SSID="${JACKPACK_AP_SSID:-JackPack}"
AP_PASSWORD="${JACKPACK_AP_PASSWORD:-}"
AP_IFACE="${JACKPACK_AP_IFACE:-}"
ATTACK_IFACE="${JACKPACK_ATTACK_IFACE:-}"
WIRED_IFACE="${JACKPACK_WIRED_IFACE:-eth0}"
LOCAL_HOSTNAME="${JACKPACK_HOSTNAME:-jackpack}"
AP_ADDRESS="${JACKPACK_AP_ADDRESS:-10.66.0.1/24}"
AP_CHANNEL="${JACKPACK_AP_CHANNEL:-6}"
WEB_PORT="${RJ_WEB_PORT:-8080}"
WS_PORT="${RJ_WS_PORT:-8765}"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --non-interactive) NON_INTERACTIVE=1 ;;
    --start-now) START_NOW=1 ;;
    --no-packages) SKIP_PACKAGES=1 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift ;;
    --ssid) AP_SSID="${2:-}"; shift ;;
    --password) AP_PASSWORD="${2:-}"; shift ;;
    --ap-iface) AP_IFACE="${2:-}"; shift ;;
    --attack-iface) ATTACK_IFACE="${2:-}"; shift ;;
    --wired-iface) WIRED_IFACE="${2:-}"; shift ;;
    --hostname) LOCAL_HOSTNAME="${2:-}"; shift ;;
    --ap-address) AP_ADDRESS="${2:-}"; shift ;;
    --channel) AP_CHANNEL="${2:-}"; shift ;;
    --web-port) WEB_PORT="${2:-}"; shift ;;
    --ws-port) WS_PORT="${2:-}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
  shift
done

require_root

if [ -z "$AP_IFACE" ]; then
  AP_IFACE="$(detect_wifi_by_path onboard wlan0)"
fi
if [ -z "$ATTACK_IFACE" ]; then
  ATTACK_IFACE="$(detect_wifi_by_path usb wlan1)"
fi
if [ -z "$AP_PASSWORD" ]; then
  AP_PASSWORD="jackpack-$(random_token)"
fi
LOCAL_HOSTNAME="$(normalize_hostname "$LOCAL_HOSTNAME")"

step "JackPack setup"
prompt AP_SSID "Control AP name" "$AP_SSID"
prompt AP_PASSWORD "Control AP password" "$AP_PASSWORD" 1
prompt AP_IFACE "Onboard/control AP interface" "$AP_IFACE"
prompt ATTACK_IFACE "External attack WiFi interface" "$ATTACK_IFACE"
prompt WIRED_IFACE "Built-in wired target interface" "$WIRED_IFACE"
prompt LOCAL_HOSTNAME "Friendly local hostname (.local)" "$LOCAL_HOSTNAME"
LOCAL_HOSTNAME="$(normalize_hostname "$LOCAL_HOSTNAME")"
prompt AP_ADDRESS "Control AP address/CIDR" "$AP_ADDRESS"
prompt AP_CHANNEL "Control AP channel" "$AP_CHANNEL"
prompt WEB_PORT "WebUI port" "$WEB_PORT"
prompt WS_PORT "WebSocket port" "$WS_PORT"

[ "${#AP_PASSWORD}" -ge 8 ] || fail "AP password must be at least 8 characters."
is_valid_hostname "$LOCAL_HOSTNAME" || fail "Invalid hostname: $LOCAL_HOSTNAME"
is_valid_port "$WEB_PORT" || fail "Invalid WebUI port: $WEB_PORT"
is_valid_port "$WS_PORT" || fail "Invalid WebSocket port: $WS_PORT"
[ -n "$INSTALL_DIR" ] || fail "Install dir cannot be empty."

step "Writing runtime config"
write_env_file /etc/packjack/packjack.env
info "Wrote /etc/packjack/packjack.env"

if [ "$SKIP_PACKAGES" -eq 0 ]; then
  install_packages
else
  warn "Skipping package installation."
fi

setup_hostname

step "Preparing install directory"
mkdir -p "$INSTALL_DIR" /etc/packjack
if [ "$ROOT_DIR" != "$INSTALL_DIR" ]; then
  rsync -a --delete \
    --exclude .git \
    --exclude loot \
    "$ROOT_DIR/" "$INSTALL_DIR/"
fi
mkdir -p "$INSTALL_DIR/loot/network"
if [ "$INSTALL_DIR" != "/root/Raspyjack" ] && [ ! -e /root/Raspyjack ]; then
  ln -s "$INSTALL_DIR" /root/Raspyjack
  info "Created legacy payload path link /root/Raspyjack -> $INSTALL_DIR"
elif [ "$INSTALL_DIR" != "/root/Raspyjack" ] && [ ! -L /root/Raspyjack ]; then
  warn "/root/Raspyjack already exists; legacy hardcoded payload paths may need manual migration."
fi
chmod +x "$INSTALL_DIR/deploy/network/packjack-ap.sh" "$INSTALL_DIR/scripts/pin_wifi_names.sh"

install_services

if [ "$START_NOW" -eq 1 ]; then
  step "Starting JackPack services"
  systemctl restart packjack-pin-wifi.service || true
  systemctl restart packjack-ap.service
  systemctl restart packjack-web.service
  systemctl restart packjack-ws.service
else
  warn "Services are enabled but not started. Reboot is recommended."
fi

cat <<EOF

JackPack install complete.

Control AP
  SSID:      $AP_SSID
  Password:  $AP_PASSWORD
  Interface: $AP_IFACE
  Address:   $AP_ADDRESS

Payload WiFi
  Interface: $ATTACK_IFACE

Wired Target
  Interface: $WIRED_IFACE

WebUI
  Friendly URL: http://$LOCAL_HOSTNAME.local:$WEB_PORT
  Fallback URL: http://${AP_ADDRESS%%/*}:$WEB_PORT

Next step:
  reboot

EOF
